USE [master]
GO

/****** Object:  Database [Achieve]    Script Date: 4/17/2022 1:12:59 PM ******/
DROP DATABASE [Achieve]
GO

/****** Object:  Database [Achieve]    Script Date: 4/17/2022 1:12:59 PM ******/
CREATE DATABASE [Achieve]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Achieve', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Achieve.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Achieve_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Achieve_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Achieve].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Achieve] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Achieve] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Achieve] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Achieve] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Achieve] SET ARITHABORT OFF 
GO

ALTER DATABASE [Achieve] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Achieve] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Achieve] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Achieve] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Achieve] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Achieve] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Achieve] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Achieve] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Achieve] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Achieve] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Achieve] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Achieve] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Achieve] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Achieve] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Achieve] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Achieve] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Achieve] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Achieve] SET RECOVERY FULL 
GO

ALTER DATABASE [Achieve] SET  MULTI_USER 
GO

ALTER DATABASE [Achieve] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Achieve] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Achieve] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Achieve] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Achieve] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Achieve] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Achieve] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Achieve] SET  READ_WRITE 
GO

